- .github/workflows/main.yml
Tohle jsme řešili včera odpoledne s tím, jak se nepropisují tagy. Bylo to tím, že tagy jsou prozatím zařazené v podsložce podle projektu a `*` to nematchne a musí tam být `**`.
> KBC-2910 fix build for tags

- packages/php-datatypes/src/Definition/Teradata.php
- packages/php-datatypes/tests/TeradataDatatypeTest.php
Jira: TER-60
Stejny kod jako [tady](https://github.com/keboola/php-datatypes/pull/64), jen presunutej do monorepa.
> Teradata by-basetype conversion

- .github/workflows/main.yml
CT-787
Part 3/3
Podpora pre split, malo by to potom fungovat out of the box alo pri libke ktora tam uz je
Otestoval som ze ked spravim zmeni v repozitaroch tak to trigne builde pre oba
https://github.com/keboola/storage-backend/actions/runs/4015192928
Ak spravim zmenu len v jednej libke tak to trigne prislusny build
https://github.com/keboola/storage-backend/actions/runs/4013455827
Part 1/3 https://github.com/keboola/storage-backend/pull/10
Part 2/3 https://github.com/keboola/storage-backend/pull/11
budem to mergovat od part 3 smerom dole az po master.
> Add to split phase

- .github/workflows/build-php-table-backend-utils.yml
- .github/workflows/main.yml
Opavujem warningy v actions 
pred 
https://github.com/keboola/storage-backend/actions/runs/4027056747
a po 
https://github.com/keboola/storage-backend/actions/runs/4027181126
php-datatypes tam nemaju ziadne
> fix github action warnings

- .gitignore
- Dockerfile
- composer.json
- docker-compose.yml
- docker/php/php.ini
- docker/php/xdebug.ini
- monorepo-builder.php
- packages/php-table-backend-utils/composer.json
- packages/php-table-backend-utils/phpstan-baseline.neon
- src/MostRecentTagWithoutRepositoryPrefixResolver.php
Pridavam
- zakladny docker aby siel nainstalovat composer
- monorepo-builder
- custom tag resolver, vyfiltruje to vsetky tagy ktore maju prefix aby slo vydat novu verziu pomocou monorepo-buildera
- je tam este tmp commit ktory zakomentoval veci ktore zalozia tag a pushnu ho aby sme pri review nahodou nieco nepushli :) 
Ako spravit review:
- vsetky commandy su tu https://github.com/symplify/monorepo-builder
- v podstate nas hlavne zaujma release `docker-compose run --rm dev vendor/bin/monorepo-builder release <tag> --dry-run`
- ide spustit v `--dry-run` mode kde to vypise len co bude robit 
- kedze sa monorepo bude vydavat potom vo verziach pre vsetky libky zaroven tzn. po mergi toho PR zavolam
`docker-compose run --rm dev vendor/bin/monorepo-builder release 7.0.0 --dry-run` verzia `7.0.0` …
> Add docker and monorepo-builder

- .github/workflows/main.yml
Opravujem build aby ked poslem tag tak sa spustil split ak upravim jednu z libiek
https://github.com/keboola/storage-backend/actions/runs/4201465770 -tag
test ak failene php7 tak to dalej nepokracuje:
https://github.com/keboola/storage-backend/actions/runs/4197024347 - nomalny build
https://github.com/keboola/storage-backend/actions/runs/4197084002  - tag 
trosku matuce je ze je potom ten `test_result` zeleny ale nic stim nespravim asi
> Fix main.yml workflow

- .github/workflows/release.yml
- monorepo-builder.php
- src/AddTagPerPackagesWhenRepoIsReleasedWorker.php
- src/AddTagPerPackagesWorker.php
https://keboola.atlassian.net/browse/CT-897
Pridavam finalnu fazu kde je mozne po merge v GH spustit rucny release a repo si vytvori svoje tagy pre kazdy repozitar a split script by sa mal postarat o ostatne.
Navod na review:
1. lokalne si spustim release, mam schvalne zakomentovane pushovanie tagov aby sa nestal omyl v dasom PR to odkomentujem a malo byt o byt potom konecne riesenie.
2. takze spustim command `docker-compose run dev bash` potom bude potreba setupnut globalney git email a meno a pustit `./vendor/bin/monorepo-builder release major`  (na CI je to vo workflow, mal som to pridane v docker file ale vlastne to nieje potreba)
3. Lokalne mi to updatne composer vzajomne naviazanych libiek na novu release verziu podla toho ci je to major, minor alebo patch
4. Commitne to zmeny
5. …
> Release and split monorepo

- packages/php-db-import-export/src/Backend/Bigquery/ToStage/FromGCSCopyIntoAdapter.php
https://keboola.atlassian.net/browse/BIG-131
Zacalo failovat BQ  https://github.com/keboola/storage-backend/actions/runs/4541408979/jobs/8025720921#step:5:79 vyzera to ze zapli autodetekciu typov pri importe s CSV, prerobil som to teda na volanie klientom namiesto SQLka, pretoze v SQLku sa neda vypnut ta autodetekcia. Potom to preslo tu https://github.com/keboola/storage-backend/actions/runs/4564780065 pripadne v dalsich buildoch robil som este nejake drobne upravy
> Use BQ methods instead of query

- packages/php-storage-driver-common/generated/GPBMetadata/Proto/Bucket.php
- packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/GrantBucketAccessToReadOnlyRoleCommand.php
- packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/RevokeBucketAccessFromReadOnlyRoleCommand.php
- packages/php-storage-driver-common/proto/bucket.proto
Na zaklade https://github.com/keboola/php-storage-driver-bigquery/pull/48#discussion_r1314674297 musim pridat este stack prefix,
Zaroven odoberam z revoke branchId pretoze neiej potreba z connection dostanem cele schema name
> Add stack prefix to GrantBucketAcces, remove branchId from revoke

- packages/php-datatypes/src/Definition/Common.php
- packages/php-datatypes/src/Definition/DefinitionInterface.php
- packages/php-db-import-export/src/Backend/Snowflake/SnowflakeException.php
- packages/php-db-import-export/src/Backend/Snowflake/SnowflakeImportOptions.php
- packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- packages/php-db-import-export/src/Backend/SourceDestinationColumnMap.php
- packages/php-db-import-export/tests/functional/Backend/Snowflake/SnowflakeExceptionTest.php
- packages/php-db-import-export/tests/functional/Snowflake/SnowflakeBaseTestCase.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/FullImportTest.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/StageToFinalCastingErrorsTest.php
- packages/php-db-import-export/tests/functional/Snowflake/ToStage/StageImportTest.php
- packages/php-db-import-export/tests/unit/Backend/SourceDestinationColumnMapTest.php
JIRA: [CT-1128](https://keboola.atlassian.net/browse/CT-1128)
[CT-1128]: https://keboola.atlassian.net/browse/CT-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1128 SNFLK autocast types when using string stage table

- packages/php-table-backend-utils/src/Column/Bigquery/Parser/ComplexTypeTokenizer.php
- packages/php-table-backend-utils/src/Column/Bigquery/Parser/ParsingComplexTypeLengthException.php
- packages/php-table-backend-utils/src/Column/Bigquery/Parser/SQLtoRestDatatypeConverter.php
- packages/php-table-backend-utils/src/Connection/Bigquery/BigQueryClientHandler.php
- packages/php-table-backend-utils/tests/Functional/Bigquery/BigqueryBaseCase.php
- packages/php-table-backend-utils/tests/Unit/Column/Bigquery/Parser/ComplexTypeTokenizerTest.php
- packages/php-table-backend-utils/tests/Unit/Column/Bigquery/Parser/SQLtoRestDatatypeConverterTest.php
JIRA: BIG-185
- Upravil sem chybové hlášky aby dávali víc smysl a aby sa vyhazovala InvalidLengthException z php-datatypes.
- přidal sem unit testy na chybové stavy, ne všecky exceptions sa mě podařilo vynutit, ale sů to reálně chybové stavy, které by mohli nějak nastat
> BIG-185 Make more sense in BQ parsing exceptions

- provisioning/AWS/aws-resources.yaml
FIXES: https://keboolaglobal.slack.com/archives/C055K9CRFDX/p1697705637528959
- Vytvoření ECR repositáře pro build 100 dní retencí images
- Pipeline role má právo na pull/push do nového ECR
Ručně updatnuto v https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A149899208592%3Astack%2Fci-storage-backend%2Fa66aabc0-b6c3-11ed-b998-1222aa0a5f73&filteringText=&filteringStatus=active&viewNested=true
> AWS build ECR

- packages/php-db-import-export/src/Backend/Bigquery/BigqueryException.php
- packages/php-db-import-export/src/Backend/Bigquery/BigqueryInputDataException.php
- packages/php-db-import-export/src/Backend/Bigquery/ToStage/FromGCSCopyIntoAdapter.php
- packages/php-db-import-export/src/Backend/Bigquery/ToStage/ToStageImporter.php
- packages/php-db-import-export/tests/functional/Bigquery/StageImportTest.php
Jira: BIG-193
Odchytavam exception, kdyz to chcipne na loadu null do not-null sloupce. Je to ve dvou usecasech (job a query) a chci k tomu vratit BigqueryInputDataException abych podle ni pak mohl v driveru vratit `ImportValidationException` ktera ma `NonRetryableExceptionInterface` (nedava smysl retry kdyz loadujes spatna data)
s tema exceptions lib-driver-connection je bordel, vubec se mi ta situace nelibi
> BIG-193 catch service exception

- packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/FullImporter.php
- packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
- packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
Jira: BIG-193
dedup table is not temp table and doing DDL on pernament objects is forbidden in transaction
https://cloud.google.com/bigquery/docs/transactions#statements_supported_in_transactions
> BIG-193 rollback transaction

- packages/php-datatypes/src/Definition/Bigquery.php
- packages/php-table-backend-utils/src/Column/Bigquery/Parser/SQLtoRestDatatypeConverter.php
- packages/php-table-backend-utils/tests/Unit/Column/Bigquery/Parser/SQLtoRestDatatypeConverterTest.php
> BIG-203 Convert types not supported in BQ REST API

- packages/php-datatypes/src/Definition/Common.php
- packages/php-datatypes/src/Definition/Snowflake.php
- packages/php-datatypes/tests/SnowflakeDatatypeTest.php
- packages/php-table-backend-utils/src/Table/Snowflake/SnowflakeTableQueryBuilder.php
- packages/php-table-backend-utils/tests/Unit/Table/Snowflake/SnowflakeTableQueryBuilderTest.php
Jira: CT-1169
Connection PR: https://github.com/keboola/connection/pull/4838
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1264
---
> CT-1169 add parsing of precision&scale to SNFLK

- packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
Jira: CT-1642
SAPI PR: XXX
---
`getUpdateWithPkCommand` now can compare GEOMETRY and GEOGRAPHY datatypes, previously it was wrong and query would fail as DISTINCT FROM cannot compare two same types.
Not it will cast them to EWKT and compare with DISTINCT FROM
> CT-1642 Fix support for GEOMETRY and GEOGRAPHY for incremental load

- packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
- packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- packages/php-db-import-export/src/ImportOptions.php
- packages/php-db-import-export/src/ImportOptionsInterface.php
- packages/php-db-import-export/tests/functional/Bigquery/BigqueryBaseTestCase.php
- packages/php-db-import-export/tests/functional/Bigquery/SqlBuildTest.php
- packages/php-db-import-export/tests/functional/Bigquery/ToFinal/IncrementalImportTest.php
- packages/php-db-import-export/tests/functional/Snowflake/SnowflakeBaseTestCase.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
- packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
Jira: CT-1424
Connection PR: https://github.com/keboola/connection/pull/5347
SAPI PR: -
---
I have dropped the dependency on `native-types_timestamp-bc` feature because it should be by default these days
-> I removed `compareAllColumnsInNativeTable` -> SQL builder has been changed so now all INC load does comparing all the columns -> all the tests had to be fixed... kill me now
tag in connection was successful https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=51963&view=results
> CT-1424 remove dependency on native types feature

- packages/php-table-backend-utils/src/Schema/Snowflake/SnowflakeSchemaReflection.php
- packages/php-table-backend-utils/tests/Functional/Snowflake/Schema/SnowflakeSchemaReflectionTest.php
Jira: [DMD-33](https://keboola.atlassian.net/browse/DMD-33)
Connection PR: https://github.com/keboola/connection/pull/5415
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1439
---
Changes:
 - add length & precision for data types
[DMD-33]: https://keboola.atlassian.net/browse/DMD-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-33 bucket refresh fix column data types

- packages/php-datatypes/src/Definition/Snowflake.php
- packages/php-datatypes/tests/SnowflakeDatatypeTest.php
- packages/php-db-import-export/src/Backend/Snowflake/ToStage/StageTableDefinitionFactory.php
https://keboola.atlassian.net/browse/SUPPORT-11491
Increase maximum VARCHAR size in Snowflake to 128MB, according to 2025_02 Bundle.
https://docs.snowflake.com/en/release-notes/bcr-bundles/2025_02/bcr-1942
CSAS has the bundle already enabled and they're trying to create a VARCHAR column with increased size, but it's failing on validation.
> Increase maximum VARCHAR size in Snowflake to 128MB

- packages/php-db-import-export/src/Backend/Snowflake/Export/AbsExportAdapter.php
- packages/php-db-import-export/src/Backend/Snowflake/Export/GcsExportAdapter.php
- packages/php-db-import-export/src/Backend/Snowflake/Export/S3ExportAdapter.php
- packages/php-db-import-export/src/Storage/ABS/SnowflakeExportAdapter.php
- packages/php-db-import-export/src/Storage/GCS/SnowflakeExportAdapter.php
- packages/php-db-import-export/src/Storage/S3/SnowflakeExportAdapter.php
- packages/php-db-import-export/tests/unit/Backend/Snowflake/Exporter/AbsExportAdapterTest.php
- packages/php-db-import-export/tests/unit/Backend/Snowflake/Exporter/GcsExportAdapterTest.php
- packages/php-db-import-export/tests/unit/Backend/Snowflake/Exporter/S3ExportAdapterTest.php
- packages/php-db-import-export/tests/unit/Storage/ABS/SnowflakeExportAdapterTest.php
- packages/php-db-import-export/tests/unit/Storage/GCS/SnowflakeExportAdapterTest.php
- packages/php-db-import-export/tests/unit/Storage/S3/SnowflakeExportAdapterTest.php
Jira: PAT-261 https://keboolaglobal.slack.com/archives/C08L30T94NM 
SAPI PR: XXX
---
COPY INTO sometimes won't return all result files. By calling result_scan on last_query_id we are fixing this problem.
It was tested that this works, it's not easy to replicate.
> PAT-261 INC_21878 use result scan

- composer.json
- packages/php-storage-driver-snowflake/README.md
- packages/php-storage-driver-snowflake/src/ConnectionFactory.php
- packages/php-storage-driver-snowflake/tests/Functional/BaseCase.php
- packages/php-storage-driver-snowflake/tests/Functional/ConnectionFactoryTest.php
- packages/php-storage-driver-snowflake/tests/Functional/ConnectionTestWithPassword.php
Jira: DMD-189
Connection PR:  https://github.com/keboola/connection/pull/6022/files
SAPI PR: -
---
support private key if the value looks like private key
> DMD-189 Support private key

- packages/php-datatypes/src/Definition/Bigquery.php
- packages/php-datatypes/tests/BigqueryDatatypeTest.php
Jira: −
Connection PR: −
SAPI PR: keboola/storage-api-php-client#1560
**Need there:** [php-storage-driver-bigquery#174](https://github.com/keboola/php-storage-driver-bigquery/pull/174/files#diff-2fea2b7eabcf453f075d41dd2c332e481a4fb7157007866e31663a739c5786a8R147)
Indirect dependeny in `Bigquery($type))->getBasetype()` where new aliases could be come from API to `$type`.
---
- New alias FLOAT for FLOAT64, BOOLEAN for BOOL.
- It's not in documentation (https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types) but works in SQL.
- It's in REST API documentation (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableFieldSchema) and based on my observations REST API returns only FLOAT or BOOLEAN.
> php-datatypes: New BigQuery alias FLOAT, BOOLEAN

- packages/php-storage-driver-snowflake/src/Profile/Column/NumericStatisticsColumnMetric.php
- packages/php-storage-driver-snowflake/tests/Functional/Handler/ProfileTableHandlerTest.php
- packages/php-storage-driver-snowflake/tests/Functional/Profile/Column/DecimalColumnMetricTest.php
- packages/php-storage-driver-snowflake/tests/Functional/Profile/Column/FloatColumnMetricTest.php
- packages/php-storage-driver-snowflake/tests/Functional/Profile/Column/NumberColumnMetricTest.php
**Jira**: DMD-433
**KBC**: [keboola/connection#6242](https://github.com/keboola/connection/pull/6242)
**SAPI**: [keboola/storage-api-php-client#1577](https://github.com/keboola/storage-api-php-client/pull/1577)
**BigQuery driver**: [keboola/php-storage-driver-bigquery#180](https://github.com/keboola/php-storage-driver-bigquery/pull/180)
---
---
**Release Notes**
- Remove mode value from table profiling numeric statistics.
**Impact analysis**
- None
**Change type**
- Fix
**Justification**
- Mode doesn't return all values for multimodal sets. Now we have no time for stable solution. So we will remove mode from numeric statistics metric.
> DMD-433 Delete mode from numeric stats profiling metric
