packages/php-datatypes/src/Definition/Bigquery.php
packages/php-datatypes/tests/BigqueryDatatypeTest.php

https://keboola.atlassian.net/browse/BIG-8
hlavna dokumentacia podla ktorej som siel https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
STRUCT a ARRAY zatial nebudeme podporovat

Add bigquery

---

README.md

Pridavam do tabulky prehladu dalsie balicky

Add info about packages to readme

---

packages/php-db-import-export/src/Backend/Synapse/ToStage/FromTableCTASAdapter.php

Mělo by to fixnout chyby na CSAS při CTAS importu (za předpokladu, že Synapse v době importu nevytuhne úplně)

make synapse FromTableCTASAdapter more robust

---

packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php

řeší částečně [PST-631](https://keboola.atlassian.net/browse/PST-631) a [CM-472](https://keboola.atlassian.net/browse/CM-472)
[PST-631]: https://keboola.atlassian.net/browse/PST-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CM-472]: https://keboola.atlassian.net/browse/CM-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PST-631 CM-472 SNFLK add missing types

---

.github/workflows/build-php-db-import-export.yml

testy presli akurat to failo na konci pretoze to chcelo robit split.

disable suite teradata tpt abs

---

packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php

CT-666 skip SNFLK value check for typed tables

---

packages/php-db-import-export/src/Backend/Snowflake/SnowflakeException.php
packages/php-db-import-export/tests/functional/Backend/Snowflake/SnowflakeExceptionTest.php

CT-1008 handle ROW_SIZE_TOO_LARGE exception for snowflake import

---

packages/php-db-import-export/src/Backend/Snowflake/SnowflakeException.php
packages/php-db-import-export/tests/functional/Backend/Snowflake/SnowflakeExceptionTest.php

CT-1044 SNFLK Convert Out of range to Import exception

---

.github/workflows/build-php-db-import-export.yml
packages/php-db-import-export/src/Backend/Assert.php
packages/php-db-import-export/src/Backend/Snowflake/ToStage/FromTableInsertIntoAdapter.php
packages/php-db-import-export/tests/functional/Snowflake/ToStage/StageImportTest.php
packages/php-db-import-export/tests/unit/Backend/AssertTest.php

CT-1055 assertSameColumns length

---

.github/workflows/build-php-db-import-export.yml
packages/php-storage-driver-common/generated/GPBMetadata/Proto/Bucket.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/CreateBucketCommand.php
packages/php-storage-driver-common/proto/bucket.proto

BIG-143 driver support branches

---

bin/split-repo.sh

multiple updates for ref 'refs/tags/SKIP' not allowed

Rename tags to uniquie skip refs to prevent

---

packages/php-storage-driver-common/contract/Driver/ClientInterface.php

Aby slo poslat z connection ten run_id tak este je potreba upravit tento iterface.

Add runtime options to client interface

---

packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/src/Backend/SourceDestinationColumnMap.php
packages/php-db-import-export/src/Exception/ColumnsMismatchException.php
packages/php-db-import-export/tests/unit/Backend/SourceDestinationColumnMapTest.php

CT-1128 sourceDestinationColumnMap now have option to map by column names

---

packages/php-datatypes/src/Definition/Bigquery.php
packages/php-datatypes/tests/BigqueryDatatypeTest.php
packages/php-db-import-export/src/Backend/Assert.php
packages/php-db-import-export/tests/functional/Bigquery/SqlBuildTest.php
packages/php-db-import-export/tests/functional/Bigquery/ToFinal/FullImportTest.php
packages/php-table-backend-utils/src/Column/Bigquery/BigqueryColumn.php
packages/php-table-backend-utils/src/Column/Bigquery/Parser/RESTtoSQLDatatypeConverter.php
packages/php-table-backend-utils/src/Column/Bigquery/RESTtoSQLDatatypeConverter.php
packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableReflection.php
packages/php-table-backend-utils/src/Table/Bigquery/ClusteringConfig.php
packages/php-table-backend-utils/src/Table/Bigquery/Partition.php
packages/php-table-backend-utils/src/Table/Bigquery/PartitioningConfig.php
packages/php-table-backend-utils/src/Table/Bigquery/RangePartitioningConfig.php
packages/php-table-backend-utils/src/Table/Bigquery/TimePartitioningConfig.php
packages/php-table-backend-utils/tests/Functional/Bigquery/Table/BigqueryTableReflectionTest.php
packages/php-table-backend-utils/tests/Unit/Column/Bigquery/BigqueryColumnTest.php
packages/php-table-backend-utils/tests/Unit/Column/Snowflake/SnowflakeColumnTest.php

BIG-169
- Table reflection používá REST API
- přidání listování partitions
- přidání partitioning a clustering do reflection

BIG-169 table reflection use REST API

---

packages/php-datatypes/src/Definition/Common.php
packages/php-datatypes/tests/BigqueryDatatypeTest.php
packages/php-table-backend-utils/src/Column/Bigquery/Parser/ComplexTypeTokenizer.php
packages/php-table-backend-utils/src/Column/Bigquery/Parser/RESTtoSQLDatatypeConverter.php
packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableReflection.php
packages/php-table-backend-utils/tests/Functional/Bigquery/Table/BigqueryTableReflectionTest.php
packages/php-table-backend-utils/tests/Unit/Column/Bigquery/BigqueryColumnTest.php
packages/php-table-backend-utils/tests/Unit/Column/Bigquery/Parser/SQLtoRestDatatypeConverterTest.php

BIG-171 BQ bug fixes

---

.github/workflows/build-php-table-backend-utils.yml
.github/workflows/main.yml

Vobec sa nepustali funkcionalne testy pre BQ a table backend utils tak som to pridal build presiel tu https://github.com/keboola/storage-backend/actions/runs/6466060577?pr=99 spadlo to na exasole

Add test bq

---

packages/php-storage-driver-common/Shared/Driver/Exception/Command/TooManyRequestsException.php

JIra: https://keboola.atlassian.net/browse/BIG-167
exception, kteoru pak vyhodi bq driver a propadne do connection, kde ji zkonvertuju na userexception

BIG-167 add exception to common driver

---

packages/php-db-import-export/src/Storage/GCS/ManifestGenerator/GcsSlicedManifestFromFolderGenerator.php
packages/php-db-import-export/src/Storage/GCS/ManifestGenerator/GcsSlicedManifestFromUnloadQueryResultGenerator.php
packages/php-db-import-export/src/Storage/SlicedManifestGeneratorInterface.php

Co som testoval tak by to malo pomoct na error `Malformed multipart body` to ze to pomohlo pisem tu https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1697714252941279
https://cloud.google.com/storage/docs/streaming-uploads#storage-stream-upload-object-php

Stream manifest instead of clasic upload

---

packages/php-datatypes/.gitignore
packages/php-datatypes/src/Definition/Oracle.php
packages/php-datatypes/tests/OracleDatatypeTest.php

JIRA: https://keboola.atlassian.net/browse/CM-727

Oracle Datatype class and its test

---

.github/workflows/build-php-db-import-export.yml
.github/workflows/main.yml
bin/tag.php

Pokračuju po https://github.com/keboola/storage-backend/pull/108

fix isReleaseTag var

---

.github/workflows/build-php-db-import-export.yml
.github/workflows/build-php-storage-driver-common.yml
.github/workflows/build-php-table-backend-utils.yml
.github/workflows/main.yml
README.md
bin/refname-callback.py
bin/split-repo.sh

[CT-1178] Cache each service image

---

packages/php-table-backend-utils/src/Connection/Bigquery/SessionFactory.php

Part of: https://keboola.atlassian.net/browse/GCP-445

bigquery - wait for session init job

---

packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/FullImporter.php
packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php

Jira: BIG-193
error can happen staging->final when loading a file. Staging table has always nullable=true
needed in https://github.com/keboola/php-storage-driver-bigquery/pull/96

BIG-193 catch service exception

---

packages/php-table-backend-utils/src/Column/ColumnCollection.php
packages/php-table-backend-utils/tests/Unit/Column/ColumnCollectionTest.php

CT-1185 increase SNFLK limit for columns  1200->10000

---

packages/php-db-import-export/src/Backend/Bigquery/BigqueryException.php
packages/php-db-import-export/tests/unit/Backend/Bigquery/BigqueryExceptionTest.php

BIG-207
https://github.com/keboola/connection/pull/4722
https://github.com/keboola/storage-api-php-client/pull/1229

BIG-207 Threat import errors as user errors

---

packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php
packages/php-table-backend-utils/src/Table/Exasol/ExasolTableReflection.php
packages/php-table-backend-utils/src/Table/Snowflake/SnowflakeTableReflection.php
packages/php-table-backend-utils/src/Table/SynapseTableReflection.php
packages/php-table-backend-utils/src/View/Exasol/ExasolViewReflection.php
packages/php-table-backend-utils/src/View/Snowflake/SnowflakeViewReflection.php
packages/php-table-backend-utils/src/View/SynapseViewReflection.php
packages/php-table-backend-utils/src/View/Teradata/TeradataViewReflection.php

Jira: CT-1285
SAPI PR: XXX
---
tady ty typy nam nejak chybi

CT-1285 add varying types

---

packages/php-datatypes/src/Definition/Bigquery.php

Jira: BIG-238
Connection PR: https://github.com/keboola/connection/pull/4871
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1278
---

[BIG-238] Handle interval datatype in REST API BQ

---

packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableQueryBuilder.php
packages/php-table-backend-utils/tests/Unit/Table/BigQuery/BigqueryTableQueryBuilderTest.php

Jira: [CT-1270](https://keboola.atlassian.net/browse/CT-1270)
Connection PR: https://github.com/keboola/connection/pull/4883/files
SAPI PR:  https://github.com/keboola/storage-api-php-client/pull/1283
storage backend command: https://github.com/keboola/storage-backend/pull/132
storage backend table utils: https://github.com/keboola/storage-backend/pull/129
BQ driver: https://github.com/keboola/php-storage-driver-bigquery/pull/117
---
[CT-1271]: https://keboola.atlassian.net/browse/CT-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CT-1270]: https://keboola.atlassian.net/browse/CT-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1271 add AlterColumn SQL builder

---

packages/php-datatypes/src/Definition/Bigquery.php
packages/php-datatypes/src/Definition/Common.php
packages/php-datatypes/src/Definition/DefinitionInterface.php
packages/php-datatypes/src/Definition/Exasol.php
packages/php-datatypes/src/Definition/GenericStorage.php
packages/php-datatypes/src/Definition/MySQL.php
packages/php-datatypes/src/Definition/Oracle.php
packages/php-datatypes/src/Definition/Redshift.php
packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/src/Definition/Synapse.php
packages/php-datatypes/src/Definition/Teradata.php
packages/php-datatypes/tests/BaseDatatypeTestCase.php
packages/php-datatypes/tests/BigqueryDatatypeTest.php
packages/php-datatypes/tests/ExasolDatatypeTest.php
packages/php-datatypes/tests/OracleDatatypeTest.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php
packages/php-datatypes/tests/SynapseDatatypeTest.php
packages/php-datatypes/tests/TeradataDatatypeTest.php

Jira: CT-1301
---
Používáme to v Connection v request objectu takže to není jinde v monorepu upravovat až v connection

CT-1301 DefinitionInterface add getDefinitionForBasetype

---

Dockerfile
packages/php-datatypes/Dockerfile
packages/php-db-import-export/Dockerfile
packages/php-storage-driver-common/Dockerfile
packages/php-table-backend-utils/Dockerfile

Jira: CT-1307
SAPI PR: XXX
---

CT-1307 use php:8.1.27-cli-bullseye

---

README.md
packages/php-storage-driver-common/generated/GPBMetadata/Proto/Bucket.php
packages/php-storage-driver-common/generated/GPBMetadata/Proto/Project.php
packages/php-storage-driver-common/generated/GPBMetadata/Proto/Workspace.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/CreateBucketCommand/CreateBucketBigqueryMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/GrantBucketAccessToReadOnlyRoleCommand/GrantBucketAccessToReadOnlyRoleBigqueryMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/LinkBucketCommand/LinkBucketBigqueryMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Bucket/ShareBucketCommand/ShareBucketBigqueryCommandMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Project/CreateProjectCommand/CreateProjectBigqueryMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Project/DropProjectCommand/DropProjectBigqueryMeta.php
packages/php-storage-driver-common/generated/Keboola/StorageDriver/Command/Workspace/CreateWorkspaceCommand/CreateWorkspaceBigqueryMeta.php
packages/php-storage-driver-common/proto/bucket.proto
packages/php-storage-driver-common/proto/project.proto
packages/php-storage-driver-common/proto/workspace.proto

Jira: [CT-242](https://keboola.atlassian.net/browse/BIG-242)
Connection PR: [CT-242](https://github.com/keboola/connection/pull/4920)
SAPI PR: XXX
https://github.com/keboola/php-storage-driver-bigquery/pull/127
---
[CT-242]: https://keboola.atlassian.net/browse/CT-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CT-242]: https://keboola.atlassian.net/browse/CT-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BIG-242 region from genericbackendcredentials

---

packages/php-db-import-export/src/Backend/Snowflake/SnowflakeImportOptions.php
packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/src/ImportOptions.php
packages/php-db-import-export/src/ImportOptionsInterface.php
packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
packages/php-db-import-export/tests/unit/ImportOptionsTest.php

Jira: CT-1320
SAPI PR: XXX
---
Udělal sem update query v inkremental loadu na features, každá feature použije jiný update stetement, cíl je to hodit do platformy a umožnit benchmark
```
import:row-change:EQUAL_NULL
import:row-change:IS_NULL
import:row-change:HASH
import:row-change:sub:COALESCE
import:row-change:DISTINCT
import:row-change:sub:IFNULL
```

CT-1320 bench

---

packages/php-db-import-export/src/Backend/Bigquery/BigqueryImportOptions.php
packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/tests/functional/Bigquery/SqlBuildTest.php

Jira: CT-1320
SAPI PR: XXX
---
Pokračování https://github.com/keboola/storage-backend/pull/140

CT-1320 BigQuery getUpdateWithPkCommand new features benchmark

---

packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableDefinition.php

Jira: [BIG-246](https://keboola.atlassian.net/browse/BIG-246)
KBC: https://github.com/keboola/connection/pull/4971
SAPI: https://github.com/keboola/storage-api-php-client/pull/1318
table utils: https://github.com/keboola/storage-backend/pull/143
---
[BIG-246]: https://keboola.atlassian.net/browse/BIG-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BIG-246 add table type

---

.github/workflows/build-php-db-import-export.yml
.github/workflows/build-php-table-backend-utils.yml

Jira: CT-1390
SAPI PR: XXX
---

CT-1390 skip synapse tests

---

packages/php-db-import-export/src/Backend/Bigquery/Export/GcsExportAdapter.php
packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/FullImporter.php
packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
packages/php-db-import-export/src/Backend/Bigquery/ToStage/FromTableInsertIntoAdapter.php
packages/php-table-backend-utils/src/Connection/Bigquery/QueryExecutor.php
packages/php-table-backend-utils/src/Schema/Bigquery/BigquerySchemaReflection.php
packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableReflection.php
packages/php-table-backend-utils/tests/Functional/Bigquery/Connection/QueryExecutorTest.php
packages/php-table-backend-utils/tests/Functional/Bigquery/Connection/SessionTest.php
packages/php-table-backend-utils/tests/Unit/Connection/BigQuery/QueryExecutorTest.php

Jira: BIG-245
SAPI PR: XXX
---

BIG-245 add QueryExecutor to improve query pooling control

---

.github/workflows/build-php-db-import-export.yml
packages/php-db-import-export/phpstan-baseline.neon
packages/php-db-import-export/src/Backend/Bigquery/BigqueryException.php
packages/php-db-import-export/src/Backend/Synapse/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/src/Storage/GCS/ManifestGenerator/GcsSlicedManifestFromFolderGenerator.php
packages/php-db-import-export/src/Storage/GCS/ManifestGenerator/GcsSlicedManifestFromUnloadQueryResultGenerator.php
packages/php-db-import-export/tests/functional/DebugLogger.php
packages/php-db-import-export/tests/functional/Synapse/SqlBuilderTest.php
packages/php-db-import-export/tests/unit/Backend/Bigquery/BigqueryExceptionTest.php
packages/php-db-import-export/tests/unit/Storage/GCS/ManifestGenerator/GCSSlicedManifestFromFolderGeneratorTest.php
packages/php-db-import-export/tests/unit/Storage/GCS/ManifestGenerator/GcsSlicedManifestFromUnloadQueryResultGeneratorTest.php

Fix phpstan

---

packages/php-db-import-export/.gitignore
packages/php-db-import-export/.terraform.lock.hcl
packages/php-db-import-export/README.md
packages/php-db-import-export/bq-storage-backend-init.tf

 Updates the BigQuery terraform script and documentation

---

bin/refname-callback.py
composer.json

Jira: CT-933
Connection PR: https://github.com/keboola/connection/pull/5004
SAPI PR: N/A
---
Tenhle PR jednak commituje vylepšené testy parseru tagů, když už jsem je udělal. Ale hlavně nastavuje replacement pro libovolnou verzimonorepo libek. V principu je to špatně (protože monorepo není kompatibilní s verzí 1 datatypes třeba, ale v principu to nevadí, protože se nainstaluje latest verze a to je to co potřebujeme.

CT-933-add-release-development-branch-tag-to-able-to-require-in-other-lib-in-process-of-programming

---

packages/php-table-backend-utils/src/Table/Bigquery/BigqueryTableReflection.php
packages/php-table-backend-utils/tests/Functional/Bigquery/Table/BigqueryTableReflectionTest.php

Jira: BIG-250
SAPI PR: XXX
---

BIG-250 BigQuery support primary keys

---

packages/php-db-import-export/src/Backend/Assert.php
packages/php-db-import-export/src/Backend/Bigquery/ToStage/FromTableInsertIntoAdapter.php
packages/php-db-import-export/tests/functional/Bigquery/StageImportTest.php
packages/php-db-import-export/tests/unit/Backend/AssertTest.php

Jira: BIG-251
SAPI PR: XXX
---

BIG-251 add new assertOption argument for Assert::assertSameColumns

---

packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/src/Backend/Snowflake/Helper/DateTimeHelper.php
packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/IncrementalImporter.php
packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/src/ImportOptions.php
packages/php-db-import-export/src/ImportOptionsInterface.php
packages/php-db-import-export/tests/functional/Bigquery/BigqueryBaseTestCase.php
packages/php-db-import-export/tests/functional/Bigquery/SqlBuildTest.php
packages/php-db-import-export/tests/functional/Bigquery/ToFinal/IncrementalImportTest.php
packages/php-db-import-export/tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php

Jira: [CT-1422](https://keboola.atlassian.net/browse/CT-1422)
SAPI PR: XXX
---
[CT-1422]: https://keboola.atlassian.net/browse/CT-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1422 [TIMESTAMP FIX] on feature "native-types_timestamp-bc" and "new-native-types" run in I/E lib IS DISTINCT FROM update

---

packages/php-db-import-export/phpstan-baseline.neon
packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/tests/Common/StubLoader/GCSLoader.php

fix calling IS DISTINCT FROM on tables without types

---

packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php

Jira: PST-1473
mimo testy jsem to otestoval i přímo ve snflk - https://connection.keboola.com/admin/projects/6231/workspaces/1156567295

Snowflake: conversion table for aliases

---

packages/php-datatypes/src/Definition/Bigquery.php
packages/php-datatypes/tests/BigqueryDatatypeTest.php

Bigquery: conversion table for aliases

---

README.md

just docs for newcomers how to release new version of package in monorepo

Document how to release a new version

---

packages/php-datatypes/src/Definition/Exasol.php
packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php
packages/php-db-import-export/README.md
packages/php-db-import-export/provisioning/src/Delete.php
packages/php-db-import-export/provisioning/src/Deploy.php
packages/php-db-import-export/src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
packages/php-db-import-export/tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
packages/php-table-backend-utils/src/Column/Snowflake/SnowflakeColumn.php
provisioning/src/Delete.php
provisioning/src/Deploy.php

Jira: https://keboola.atlassian.net/browse/CT-1526
Connection PR: https://github.com/keboola/connection/pull/5195
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1381
---

CT-1526 add snowflake vector datatype

---

packages/php-table-backend-utils/src/Connection/Bigquery/BigQueryClientWrapper.php

add retry on BigQueryClientWrapper startJob call this should prevent Oauth errors

add retry to BigQueryClientWrapper startJob call

---

.github/workflows/build-php-datatypes.yml
.github/workflows/build-php-db-import-export.yml
.github/workflows/build-php-table-backend-utils.yml
.github/workflows/main.yml
.github/workflows/release.yml

Jira:  CT-1792
SAPI PR: XXX
---
update gh actions/checkout

CT-1792 update actions

---

packages/php-datatypes/src/Definition/Snowflake.php
packages/php-datatypes/src/Definition/Teradata.php
packages/php-datatypes/tests/SnowflakeDatatypeTest.php

Jira: CT-1820
SAPI PR: XXX
---
- when snowflake column is NUMBER(38,0) basetype in connection will be INTEGER

CT-1820 Snowflake TYPE_NUMBER with length 38,0 has basetype integer

---

packages/php-db-import-export/src/Backend/Bigquery/ToFinalTable/FullImporter.php

Jira: CT-1843
SAPI PR: XXX
---

CT-1843 run full import truncate in transaction

---

packages/php-table-backend-utils/src/Connection/Bigquery/BigQueryClientWrapper.php

Jira: CT-1894
SAPI PR: XXX
---

CT-1894 allow customize number of reties and backoff policy for runJob

---

packages/php-db-import-export/tests/functional/Bigquery/BigqueryBaseTestCase.php
packages/php-table-backend-utils/src/Connection/Bigquery/Retry.php
packages/php-table-backend-utils/tests/Functional/Bigquery/BigqueryBaseCase.php
packages/php-table-backend-utils/tests/Unit/Connection/Bigquery/RetryTest.php

Jira: CT-1842
SAPI PR: XXX
---
- Move Retry class from driver https://github.com/keboola/php-storage-driver-bigquery/blob/40a44eaf48e2b9c5ab81cc572dc011ad9edce818/src/Client/BigQuery/Retry.php

CT-1842 add Retry class for BQ

---

packages/php-table-backend-utils/src/Schema/Snowflake/SnowflakeSchemaReflection.php
packages/php-table-backend-utils/tests/Functional/Snowflake/Schema/SnowflakeSchemaReflectionTest.php

Jira: [DMD-59](https://keboola.atlassian.net/browse/DMD-59)
SAPI PR: XXX
---
Changelog:
- add test for SnowflakeSchemaReflection::getDefinitions()
- fix bug for VECTOR - new implementation do not return properly length for VECTOR
[DMD-59]: https://keboola.atlassian.net/browse/DMD-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DMD-58 - Snowflake datatype test

---

.github/workflows/build-php-datatypes.yml
.github/workflows/build-php-db-import-export.yml
.github/workflows/release.yml
Dockerfile
composer.json
packages/php-datatypes/Dockerfile
packages/php-datatypes/composer.json
packages/php-db-import-export/Dockerfile
packages/php-db-import-export/composer.json
packages/php-storage-driver-common/Dockerfile
packages/php-storage-driver-common/Shared/Utils/Password.php
packages/php-storage-driver-common/composer.json
packages/php-storage-driver-common/contract/Driver/Exception/NonRetryableExceptionInterface.php
packages/php-table-backend-utils/composer.json

Jira: CT-1327
SAPI PR: XXX
---
update php to be aligned with connetion. will make major update for all packages

update php to 8.3

---

packages/php-db-import-export/composer.json
packages/php-table-backend-utils/composer.json

update deps after major releases

---

.github/workflows/main.yml
packages/php-storage-driver-snowflake/LICENSE
packages/php-storage-driver-snowflake/README.md

Jira: DMD-101
---
- Adopt repo "keboola/php-storage-driver-snowflake".
- Setup monorepo split.

Add new package keboola/php-storage-driver-snowflake

---

bin/Dockerfile

Jira: CT-XXX
SAPI PR: XXX
---
Predchadzajuci [PR](https://github.com/keboola/storage-backend/pull/217) nepomohol skusam este toto

add safe.dir /monorepo/.git

---

bin/split-repo.sh

also echo ABSOLUTE_SOURCE_PATH for debug
Jira: CT-XXX
SAPI PR: XXX
---
Riesim to tu https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1753873603380559

safe dir realpath

---

bin/split-repo.sh

Jira: CT-XXX
SAPI PR: XXX
---
Este opravujem jak sme sa dohodli s @vojtabiberle https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1753888034371419?thread_ts=1753873603.380559&cid=C0553EM2RGX 
Odoberam teda povodne zmeny a prehadzujem len riadky
```
git clone --no-local --mirror "${ABSOLUTE_SOURCE_PATH}" $TMP_DIR
cd $TMP_DIR
```
na
```
cd $TMP_DIR
git clone --no-local --mirror "${ABSOLUTE_SOURCE_PATH}" $TMP_DIR
```

remove latest fix and only switch lines to fix it properly

---

README.md

**Release Notes**
- Add missing link to `keboola/storage-driver-snowflake` to README.md overview.
- Change package names to their Composer names in README.md overview.
**Impact analysis**
- None
**Change type**
- documentation
**Justification**
- We want up to date and consistent documentation.

Add link to keboola/storage-driver-snowflake to README.md
